//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bootstrapTheme.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations; 
    
    public partial class User
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is mandatory")]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "This field is mandatory")]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "This field is mandatory")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This field is mandatory")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Compare("Password")]
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        public string Confirmpassword { get; set; }
    }
}
